[phases.setup]
nixPkgs = ["nodejs_22", "openssl"]

[phases.install]
cmds = ["corepack enable && pnpm i --frozen-lockfile"]

[phases.build]
cmds = ["pnpm prisma generate && pnpm build"]

[start]
cmd = "pnpm start"
