[phases.setup]
nixPkgs = ["nodejs_22", "openssl"]

[phases.install]
cmds = ["npm install -g pnpm@10.28.2 && pnpm i --frozen-lockfile"]

[phases.build]
cmds = ["pnpm prisma generate && pnpm build"]

[start]
cmd = "pnpm start"
